### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Next#2]
How exactly the citation command works ? Is the a shortcode to add in the show.php page?

**Comment by Daniel-KM** [comment]
C'est un view helper à ajouter dans le thème : `echo $this->citation($resource);`. (https://github.com/Daniel-KM/Omeka-S-module-Next/blob/master/src/View/Helper/Citation.php)

**Comment by pprw** [comment]
Merci, ça fonctionne bien.
