### ISSUE TITLE
Site Configuration not work after install module

### ISSUE THREAD

**Issue by psalido** [Daniel-KM/Omeka-S-module-Next#3]
After install Next-3.1.2.10.zip, I get this error on site configuration page:

Log on application.log is:

2019-07-16T22:44:17+00:00 ERR (3): Error: Call to undefined method Omeka\Mvc\Controller\Plugin\CurrentSite::id() in /sites/memoria_santisteban/omeka-s/modules/Next/src/Generic/AbstractModule.php:329
Stack trace:
#0 /sites/memoria_santisteban/omeka-s/modules/Next/src/Generic/AbstractModule.php(161): Generic\AbstractModule->handleAnySettings(Object(Zend\EventManager\Event), 'site_settings')
#1 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Generic\AbstractModule->handleSiteSettings(Object(Zend\EventManager\Event))
#2 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#3 /sites/memoria_santisteban/omeka-s/application/src/Form/SiteSettingsForm.php(216): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#4 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerV3Polyfill.php(235): Omeka\Form\SiteSettingsForm->init()
#5 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(779): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit(Object(Zend\ServiceManager\ServiceManager), Object(Omeka\Form\SiteSettingsForm))
#6 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('Omeka\\Form\\Site...')
#7 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(152): Zend\ServiceManager\ServiceManager->get('Omeka\\Form\\Site...')
#8 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php(50): Zend\ServiceManager\AbstractPluginManager->get('Omeka\\Form\\Site...', NULL, true)
#9 /sites/memoria_santisteban/omeka-s/application/src/Mvc/Controller/Plugin/GetForm.php(33): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->get('Omeka\\Form\\Site...', NULL)
#10 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke('Omeka\\Form\\Site...')
#11 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(276): call_user_func_array(Object(Omeka\Mvc\Controller\Plugin\GetForm), Array)
#12 /sites/memoria_santisteban/omeka-s/application/src/Controller/SiteAdmin/IndexController.php(118): Zend\Mvc\Controller\AbstractController->__call('getForm', Array)
#13 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\SiteAdmin\IndexController->settingsAction()
#14 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#17 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /sites/memoria_santisteban/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#21 /sites/memoria_santisteban/omeka-s/index.php(21): Zend\Mvc\Application->run()
#22 {main}

**Comment by Daniel-KM** [comment]
Yes, this is an issue I saw some time ago. Update to the last version of the module and update the module Generic too if needed.

**Comment by Daniel-KM** [comment]
[Version 3.1.2.11](https://github.com/Daniel-KM/Omeka-S-module-Next/releases/tag/3.1.2.11)

**Comment by psalido** [comment]
Works fine. Thanks!!
